version: '3'
services: 
  web:
    image: docker-node-express-mongoapp
    build: .
    command: node index.js
    ports:
      - "7000:7000"
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"